basecamp/kamal-proxy

- README.md
- example/README.md
- internal/cmd/deploy.go
- internal/server/error_page_middleware.go
- internal/server/service.go
While reading the source of the project, I found a few typos here and there.
> Fixed several typos in comments and documentation

- .github/workflows/ci.yml
The `actions/checkout@v3` and `actions/setup-go@v4` use an deprecated Node.js version, causing a warning message to appear with each run. This PR updates these actions to the latest version, which utilizes Node.js 20 instead of 16.
> Update CI actions to the latest version due to deprecated node version

- internal/cmd/deploy.go
- internal/server/commands.go
- internal/server/router.go
- internal/server/router_test.go
- internal/server/service.go
- internal/server/service_test.go
- internal/server/testing.go
This adds the ability to associate multiple hostnames with a single service. For example:
kamal-proxy deploy myapp --target=web-1 --host=app.example.com,api.example.com
You can use a comma-delimited list in the `host` flag, and/or specify the flag multiple times.
When a service has multiple hostnames, requests to any of those hostnames will route to the service. If the service also specifies `--tls`, then all of the host names will be covered in the TLS certificates.
Closes #14.
> Allow multiple hosts per service

- internal/server/target_test.go
Addresses a data race in the server tests.
To reproduce:
```bash
go test ./... -race
```
Output before the change:
```
==================
WARNING: DATA RACE
Read at 0x00c000536398 by goroutine 589:
github.com/basecamp/kamal-proxy/internal/server.TestTarget_DrainRequestsThatCompleteWithinTimeout.func1()
/Users/dmytro/work/github/kamal-proxy/internal/server/target_test.go:246 +0x40
net/http.HandlerFunc.ServeHTTP()
/Users/dmytro/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.darwin-arm64/src/net/http/server.go:2220 +0x48
net/http.serverHandler.ServeHTTP()
/Users/dmytro/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.darwin-arm64/src/net/http/server.go:3210 +0x2a8
net/http.(*conn).serve()
/Users/dmytro/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.darwin-arm64/src/net/http/server.go:2092 …
```
> Addressed a data race condition in the server tests

- README.md
- internal/cmd/deploy.go
- internal/server/cert.go
- internal/server/cert_test.go
- internal/server/service.go
- internal/server/service_test.go
In some cases it is needed to use a custom TLS certificate:
* For Cloudflare origin TLS
* In a corporate environment with custom certificate authority (CA)
* In a development environment with self-signed certificate
* In cloud development environment and end to end testing pipelines
* Some people still purchase certificates from "trusted vendor™"
With Traefic we had an option to specify a custom certificate, and so this change brings this feature into kamal-proxy.
~~PS. I am still looking into adding tests, wanted to gauge opinions whether this is a feature you are interested in.~~ 
_covered by tests now_
* https://github.com/basecamp/kamal/pull/969
* https://github.com/basecamp/kamal-site/pull/100
> Added option to use custom TLS certificates instead of ACME

- internal/server/logging_middleware.go
- internal/server/response_buffer_middleware.go
- internal/server/target.go
- internal/server/target_test.go
SSE requires being able to flush the response stream as each message is written. Response buffering gets in the way of this -- the messages will be flushed into the buffer, but the client won't see any of them until the response is closed.
To support SSE while allowing the use of response buffering elsewhere, we can add a bypass for responses that have `Content-Type: text/event-stream` that prevents them being buffered.
We'll also need to make sure that any custom `ResponseWriter`s in the handler are `Flush`-able.
Fixes #34.
> Don't buffer SSE responses

- internal/server/router.go
- internal/server/router_test.go
- internal/server/service.go
This allows routing to wildcard subdomains by specifying a target like:
--target=*.example.com
This matches requests to hosts with any subdomain in place of the `*`. It does *not* match multiple levels of subdomain to a single `*`, nor are multiple `*` allowed in a single host. Rather it behaves much like the wildcard matching in TLS certificates does.
Automatic TLS is not currently supported with wildcard hosts (because the challenge types we use -- `http-01` and `tls-alpn-01` -- can't be used to generate wildcard certificates). However you can bring your own wildcard certificates using `--tls-certificate-path` / `--tls-private-key-path`.
cc @djmb 
Closes #30
> Allow routing to wildcard subdomains

- internal/server/response_buffer_middleware.go
- internal/server/response_buffer_middleware_test.go
If the content type of an event stream includes a charset, we were failing to detect it, and thus failing to disable buffering automatically for that response. We should be ignoring the charset portion when matching.
Fixes #54.
> Detect event-stream content type properly

- internal/server/target.go
- internal/server/target_test.go
Previously a client-cancelled request was logged as a proxy error, which is misleading. We can instead log it as 499, which is unambiguous and matches a convention used elsewhere.
Another situation in which requests may be cancelled is where we're forced to terminate incomplete requests during draining, because the drain timeout has expired before they've completed. In that case, we'll respond with a 504 Gateway Timeout, and log some additional context for clarity.
Closes #59
> Log a status of 499 if the client cancels the request

- internal/server/request_start_middleware.go
- internal/server/request_start_middleware_test.go
- internal/server/server.go
Implements #69
Note: I never wrote a line of Go before. I based everything on the `X-Request-ID` middleware implementation.
PS: `make test` passes for me locally
> Adds middleware to insert X-Request-Start unix millis timestamp

- internal/server/health_check.go
Per golang documentation, it isn't enough just to close the response body.
It's the best to read it before closing. Otherwise, there could be the resource leakage.
More information at <https://pkg.go.dev/net/http#Client.Do>
> read http response body before closing it

- internal/server/testing.go
- Switch to using testing.TB interface instead of \*testing.T.
- Add t.Helper() to helper functions to ensure failure reports point to
correct test lines.
- Use the standard t.TempDir() for a temporary folder creation.
- Ensure errors are checked when starting the test server.
> Improve testing helper functions

- internal/server/server.go
- internal/server/util.go
For some reason, the httpsServer does not shut down when server.Stop is called.
> Enable graceful shutdown for https server

- internal/cmd/deploy.go
- internal/server/service.go
- internal/server/service_test.go
Adds an option to disable the automatic HTTP -> HTTPS redirect when TLS is enabled for a service.
This option is off by default (i.e. the redirect is in place), but can be set on if you need to run a service as both HTTP and HTTPS.
Fixes #89
> Add `--tls-disable-redirect`

- README.md
- internal/cmd/deploy.go
- internal/cmd/list.go
- internal/server/commands.go
- internal/server/router.go
- internal/server/router_test.go
- internal/server/service.go
- internal/server/service_map.go
- internal/server/service_map_test.go
- internal/server/service_test.go
- internal/server/target.go
Building on the idea presented in #93, this provides the ability to deploy a service under a specific path.
- Adds a new `--path-prefix` option for deployments. When specified, only requests beginning with that prefix will be routed to the service. This allows multiple services to share the same host(s), by routing traffic according to the path.
- `--path-prefix` needn't be a single path segment, but the prefix must split on a path boundary. For example, a prefix of `/api/internal` is valid, and will match a path of `/api/internal/users/123`, or `/api/internal`; but it would not match `/api/internal2`.
- By default, the prefix will be removed before forwarding the request to the target service. So, given a `--path-prefix=/api`, a request to `/api/users` will reach the target as `/users`. …
> Path-based routing

- internal/cmd/deploy.go
- internal/cmd/rollout_deploy.go
- internal/server/commands.go
- internal/server/health_check.go
- internal/server/load_balancer.go
- internal/server/load_balancer_test.go
- internal/server/rollout_controller_test.go
- internal/server/router.go
- internal/server/router_test.go
- internal/server/server_test.go
- internal/server/service.go
- internal/server/service_map.go
- internal/server/service_map_test.go
- internal/server/service_test.go
- internal/server/target.go
- internal/server/target_test.go
- internal/server/testing.go
Adds the ability to deploy multiple targets per service. Requests are routed to the targets on a round-robin basis.
For a multi-target deployment to succeed, all of the targets must become healthy within the timeout. If any fails to do so, the deployment fails, and the previous set of targets is kept. After deployment, we continue to monitor the health of each target, moving them in and out of the healthy pool as necessary so that we avoid routing requests onto unhealthy targets.
As part of this change we also refactor some of a service's settings into its `ServiceOptions`, to provide a better separation between the service itself and the options that it's been configured with.
Closes #15
> Load balancing via multiple service targets

- internal/cmd/deploy.go
- internal/cmd/rollout_deploy.go
- internal/server/commands.go
- internal/server/health_check.go
- internal/server/load_balancer.go
- internal/server/load_balancer_test.go
- internal/server/router.go
- internal/server/router_test.go
- internal/server/service.go
- internal/server/service_test.go
- internal/server/target.go
- internal/server/target_test.go
- internal/server/testing.go
In addition to specifying one or more `--target` servers to deploy, you can now also specify one or more `--read-target`. When any read targets are present, traffic will be routed such that read requests go to read targets, and write requests go to write targets.
A read request is defined as a `GET` or `HEAD`, and excludes WebSocket traffic. Everything else is considered to be a write request.
Read requests that immediately follow a write on the same session will also be treated as writes. In configurations where readers are replicas of writers, this helps avoid problems where replication lag leads to a client failing to read an item it just wrote. This "writer affinity" is controlled by a cookie, and by default the effect lasts for 3 seconds. It can be adjusted via …
> Allow splitting reads/writes when load balancing

- .dockerignore
- Dockerfile
This change adds a new `.dockerignore` that excludes everything by default—then whitelists only the files we actually need (`/cmd`, `/internal`, `go.mod`, `go.sum`, and `Makefile`). By pruning the build context like this, we send far less data to the Docker daemon on every build.
The `Dockerfile` itself has been refactored to make better use of Docker’s layer cache. We now copy in just `go.mod` and `go.sum` first and run `go mod download`, so your dependencies stay cached unless they actually change. The rest of the source code is copied afterward, and we’ve consolidated the user setup, directory creation, and permission adjustments into a single `RUN` instruction. All Docker keywords are properly capitalized and blank lines separate logical stages, with no inline comments to keep things …
> Prune build context and optimize layer caching

- README.md
Necessary to document the --health-check-path parameter.
Useful for apps like Plex that return a 401 status response code on the root URL but would return 200 with the correct health check path.
> Documenting --health-check-path parameter

- internal/server/load_balancer.go
- internal/server/load_balancer_test.go
In cases where a write should be excluded from triggering writer affinity, a client can set the header `X-Writer-Affinity=false`. This can be useful for certain requests, like beacons, that result in unnecessary pinning to the writer because the result of those requests isn't visible on the page (meaning that the risk of reading stale data after writing doesn't apply).
> Skip writer affinity via header

- .github/workflows/ci.yml
let's just use the same go version numbers that specified in go.mod for ci.
> ci: get go version from go.mod for ci/cd

- internal/server/response_buffer_middleware.go
- internal/server/response_buffer_middleware_test.go
The current response buffer middleware only bypasses buffering for `text/event-stream`, 
but many legitimate streaming use cases use `Transfer-Encoding: chunked` with other 
content types:
- Long-polling applications (like MessageBus) https://github.com/discourse/message_bus 
- Streaming JSON APIs  
- Real-time log streaming
- Progressive downloads
When a server explicitly sets `Transfer-Encoding: chunked`, it's indicating the 
response is being generated dynamically. Buffering such responses can:
1. **Break streaming semantics** - Defeats the purpose of chunked encoding
2. **Increase latency** - Delays delivery of streaming data
3. **Cause application failures** - As experienced with MessageBus deployment
While RFC 7230 doesn't explicitly forbid proxy buffering of chunked responses, 
it …
> fix: respect Transfer-Encoding chunked for streaming responses

- README.md
- internal/cmd/deploy.go
- internal/server/service.go
- internal/server/target.go
- internal/server/target_test.go
- internal/server/testing.go
Hi Basecamp team,
I'm currently facing similar issue with what have been discussed in these posts:
- https://github.com/basecamp/kamal-proxy/discussions/132
- https://github.com/basecamp/kamal/issues/1234
Essentially, I'm trying to deploy an open source project ([vector](https://github.com/vectordotdev/vector)) using Kamal, but vector only supports health check that [lives in different port](https://github.com/vectordotdev/vector/issues/5710). 
Since our team already invested in Kamal, it would be a bummer to move our setup to different tools.
Would it be acceptable to allow port customization as proposed in this PR? Do let me know if you need me to approach things differently. I will also raise a PR to kamal if this is approved.
Thank You,
> Custom health check port

- internal/server/router_test.go
- internal/server/service.go
Hi 👋 
Just a minor change in the interaction with the router, I kept it simple.
Recently we had a bad configuration on our deployment. The proxy was able to prevent any of the bad configuration to be used or to influence any of the running services, yet we noticed the state was updated to reflect the bad configuration. 
If there would have been a restart of the proxy for any particular reason this bad configuration might have caused the system to not boot up properly.
> Prevent saving invalid configuration on deploy
